name: Windows Test

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-latest, windows-latest]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      # - name: 拉取代码
      #   uses: actions/checkout@v2
      # - name: 设置 Node 环境
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16
      - name: 测试环境
        run: |
          # go version
          # go install github.com/minio/mc@latest
          ./mc.exe --help
      # - name: 安装 Go 环境
      #   run: |
      #     # git clone https://go.googlesource.com/go goroot
      #     # cd goroot
      #     # git checkout master
      #     # cd src
      #     # ./all.bat
      #     go version
      # - name: Windows 环境
      #   if: matrix.platform == 'windows-latest'
      #   run: |
      #     curl https://dl.min.io/client/mc/release/windows-amd64/mc.exe
      #     dir
      #     mc.exe --help